name: Benchmarks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  jvm-benchmarks:
    strategy:
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    name: "JVM / ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew :benchmarks:jvmRun
        env:
          OPERATIONS_COUNT: 1000000
          TEST_REPETITIONS: 10
      - name: Append Table to Summary on Linux/macOS
        if: runner.os != 'Windows'
        run: cat benchmarks/build/benchmark/table.txt >> $GITHUB_STEP_SUMMARY
      - name: Append Table to Summary on Windows
        if: runner.os == 'Windows'
        run: Get-Content benchmarks\build\benchmark\table.txt | ForEach-Object { Add-Content -Path $Env:GITHUB_STEP_SUMMARY -Value $_ }

  native-benchmarks:
    strategy:
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    name: "Native / ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew runNativeBenchmark
        env:
          OPERATIONS_COUNT: 1000000
          TEST_REPETITIONS: 10
      - name: Append Table to Summary on Linux/macOS
        if: runner.os != 'Windows'
        run: cat benchmarks/build/benchmark/table.txt >> $GITHUB_STEP_SUMMARY
      - name: Append Table to Summary on Windows
        if: runner.os == 'Windows'
        run: Get-Content benchmarks\build\benchmark\table.txt | ForEach-Object { Add-Content -Path $Env:GITHUB_STEP_SUMMARY -Value $_ }