name: Benchmarks

on: [ push, pull_request ]

jobs:
  benchmarks:
    strategy:
      matrix:
        os: [ ubuntu, windows, macos ]
        release: [ true, false ]
    runs-on: ${{ matrix.os }}-latest
    name: "[${{ matrix.release == true && 'RELEASE' || 'DEBUG' }}] Benchmark ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew runBenchmark "-Pleveldb.release=${{ matrix.release }}"
        env:
          OPERATIONS_COUNT: 1000000
          TEST_REPETITIONS: 10
      - name: Append Table to Summary on Linux/macOS
        if: runner.os != 'Windows'
        run: cat benchmarks/build/benchmark/table.txt >> $GITHUB_STEP_SUMMARY
      - name: Append Table to Summary on Windows
        if: runner.os == 'Windows'
        run: Get-Content benchmarks\build\benchmark\table.txt | ForEach-Object { Add-Content -Path $Env:GITHUB_STEP_SUMMARY -Value $_ }