name: Lint check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Lint code"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew ktlintCheck
