name: Publish

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  env:
    SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
    SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  publish-artifacts:
    strategy:
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    name: "Publish artifacts on ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew publishToSonatype -Pleveldb.release=true

  close-staging-repository:
    needs: [ publish-artifacts ]
    runs-on: ubuntu-latest
    name: "Close Sonatype Staging Repository"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew closeAndReleaseSonatypeStagingRepository