name: Publish

on:
  push:
  release:
    types: [ published ]

jobs:
  create-staging-repository:
    runs-on: ubuntu-latest
    name: "Create Sonatype Staging Repository"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew initializeSonatypeStagingRepository

  publish-artifacts:
    needs: [ create-staging-repository ]
    strategy:
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    name: "Publish artifacts on ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew platformSpecificPublishAllPublicationsToSonatypeRepository -Pleveldb.release=true

  close-staging-repository:
    needs: [ publish-artifacts ]
    runs-on: ubuntu-latest
    name: "Close Sonatype Staging Repository"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew closeAndReleaseSonatypeStagingRepository