name: Pull requests checks

on: [ push, pull_request ]

jobs:
  tests:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        release: [true, false]
    runs-on: ${{ matrix.os }}
    name: "[${{ matrix.release == true && 'RELEASE' || 'DEBUG' }}] ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Install Rosetta 2
        if: matrix.os == 'macos-latest'
        run: softwareupdate --install-rosetta --agree-to-license
      - run: ./gradlew :platformSpecificTest --stacktrace -Pleveldb.release=${{ matrix.release }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-results-${{ matrix.os }}
          path: build/reports